version: '2'
services:
  php:
    container_name: feed_merger
    build: ./docker/php
    ports:
      - "8080:80"
    volumes:
      - .:/www

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - { subnet: "192.200.99.0/24", gateway: "192.200.99.1" }
